export { default as Home } from "./Home.jsx";
export { default as Error } from "./Error.jsx";
export { default as Overview } from "./Overview.jsx";
export { default as Tour } from "./Tour.jsx";
export { default as Login } from "./Login.jsx";
export { default as Signup } from "./Signup.jsx";
export { default as ForgotPass } from "./ForgotPass.jsx";
export { default as ResetPass } from "./ResetPass.jsx";
export { default as Account } from "./Account.jsx";
